# Generated by Django 2.0 on 2018-12-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newswebsite', '0003_auto_20181226_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '目录分类', 'verbose_name_plural': '目录分类'},
        ),
    ]
